2021-01-26 15:24:52,886 INFO    MainThread:1736 [wandb_setup.py:_flush():70] setting env: {}
2021-01-26 15:24:52,887 INFO    MainThread:1736 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-26 15:24:52,887 INFO    MainThread:1736 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-26 15:24:52,887 INFO    MainThread:1736 [wandb_init.py:_log_setup():303] Logging user logs to /workspace/sts-lstm-siamese/wandb/run-20210126_152452-1sfogov6/logs/debug.log
2021-01-26 15:24:52,888 INFO    MainThread:1736 [wandb_init.py:_log_setup():304] Logging internal logs to /workspace/sts-lstm-siamese/wandb/run-20210126_152452-1sfogov6/logs/debug-internal.log
2021-01-26 15:24:53,791 INFO    MainThread:1736 [wandb_run.py:_console_start():1237] atexit reg
2021-01-26 15:24:53,792 INFO    MainThread:1736 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-26 15:24:53,792 INFO    MainThread:1736 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-26 15:24:53,792 INFO    MainThread:1736 [redirect.py:install():204] install start
2021-01-26 15:24:53,793 INFO    MainThread:1736 [redirect.py:install():219] install stop
2021-01-26 15:24:53,793 INFO    MainThread:1736 [redirect.py:install():204] install start
2021-01-26 15:24:53,793 INFO    MainThread:1736 [redirect.py:install():219] install stop
2021-01-26 15:24:53,793 INFO    MainThread:1736 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-26 15:24:59,025 INFO    MainThread:1736 [wandb_watch.py:watch():35] Watching
2021-01-26 15:25:04,050 INFO    MainThread:1736 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-26 15:25:04,050 INFO    MainThread:1736 [wandb_run.py:_restore():1179] restore
2021-01-26 15:25:04,050 INFO    MainThread:1736 [redirect.py:uninstall():223] uninstall start
2021-01-26 15:25:04,050 INFO    MainThread:1736 [redirect.py:_stop():278] _stop: stdout
2021-01-26 15:25:04,050 INFO    MainThread:1736 [redirect.py:_stop():284] _stop closed: stdout
2021-01-26 15:25:04,050 INFO    stdout    :1736 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-26 15:25:04,050 INFO    stdout    :1736 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-26 15:25:04,050 INFO    MainThread:1736 [redirect.py:_stop():290] _stop joined: stdout
2021-01-26 15:25:04,050 INFO    MainThread:1736 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-26 15:25:04,051 INFO    MainThread:1736 [redirect.py:uninstall():227] uninstall done
2021-01-26 15:25:04,051 INFO    MainThread:1736 [redirect.py:uninstall():223] uninstall start
2021-01-26 15:25:04,051 INFO    MainThread:1736 [redirect.py:_stop():278] _stop: stderr
2021-01-26 15:25:04,051 INFO    MainThread:1736 [redirect.py:_stop():284] _stop closed: stderr
2021-01-26 15:25:04,051 INFO    stderr    :1736 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-26 15:25:04,051 INFO    stderr    :1736 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-26 15:25:04,051 INFO    MainThread:1736 [redirect.py:_stop():290] _stop joined: stderr
2021-01-26 15:25:04,051 INFO    MainThread:1736 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-26 15:25:04,051 INFO    MainThread:1736 [redirect.py:uninstall():227] uninstall done
2021-01-26 15:25:04,052 INFO    MainThread:1736 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "5d982aa1e2ab43f2a3af6ad2e1932222"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 736
      total_bytes: 736
    }
  }
}

2021-01-26 15:25:06,058 INFO    MainThread:1736 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "d922c3cbeb314898904dc5920bb4e233"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3371
      total_bytes: 3371
    }
  }
}

2021-01-26 15:25:07,117 INFO    MainThread:1736 [wandb_run.py:_show_files():1536] logging synced files
2021-01-26 15:25:07,118 INFO    MainThread:1736 [internal.py:handle_exit():138] Internal process exited
